id: P003185
initial_creation_type: ocr
source_metadata:
  id: bdr:W22041
  title: འཁྲུངས་སྐོར།
  author: ''
  volumes:
    bae967e373c74fd689eee2f1dd409d03:
      image_group_id: I1KG15916
      title: ''
      volume_number: 1
      total_pages: 188
